train:
  use_sampler: False
  shuffle: True
  pin_memory: False
  drop_last: False
  num_workers: 8
  prefetch_factor: 16
  batch_size: 64

valid:
  use_sampler: False
  shuffle: True
  pin_memory: False
  drop_last: False
  num_workers: 8
  prefetch_factor: 16
  batch_size: 64

test:
  use_sampler: False
  shuffle: False
  pin_memory: False
  drop_last: True
  num_workers: 16
  batch_size: 64