name: ImageLabelDataset

config:
  enums_class: BenignMalignantDatasetLabels # one of {BenignMalignantDatasetLabels, HasArchDistortion, HasCalcification, HasMassLabels} 
  search_col: image_label # one of {image_label, has_architectural_distortion, has_calc, has_mass}
  generate_label_prompt_sentence: False
  generate_label_prompt_report: False

  base_dataset_path: /storage/Features/features/png_archive/2D_100micron/0/
  annotated_dataset_path: data/02_data_T_regions
  lists_dataset_path: data/02_data_lists/data/lists

eval:
  enum_classes: ["BenignMalignantDatasetLabels"] # one or all of {BenignMalignantDatasetLabels, HasArchDistortion, HasCalcification, HasMassLabels}
  method: ["ova", "zeroshot_label_prompt", "confustion_matrix"]

  dataset:
    name: ImageLabelDataset # for sentences, we evaluate with the label datasets

split:  
  train_split_ratio: 0.7
  test_split_ratio: 0.5

template:
  prompt_template: ""
  label: []
  template_keys: []